sudo: required
services:
  - docker

before_install:
  - docker build -t dyle/frontend -f Dockerfile.dev .

script:
  - docker run dyle/frontend npm run test -- --coverage

deloy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    brach: main